/*
 * File: app/view/MainLayout.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TechinTalk.view.MainLayout', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mainlayout',

    requires: [
        'TechinTalk.view.MainLayoutViewModel',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'mainlayout'
    },
    height: '',
    width: '',
    layout: 'fit',
    title: '',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            bodyPadding: 10,
            title: 'Login',
            titleAlign: 'center',
            layout: {
                type: 'vbox',
                align: 'center'
            },
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: 'Username'
                },
                {
                    xtype: 'textfield',
                    maskElement: '',
                    fieldLabel: 'Password',
                    inputType: 'password'
                },
                {
                    xtype: 'button',
                    flex: 1,
                    width: '',
                    text: 'Sign in',
                    listeners: {
                        click: 'onButtonClick'
                    }
                }
            ]
        }
    ],

    onButtonClick: function(button, e, eOpts) {
        var form = button.up().getForm();
        var values = form.getValues();
        var fieldValues = Object.values(values);

        var userName = fieldValues[0];
        var password = fieldValues[1];

        //var userName = values["textfield-1012-inputEl"];
        //var password = values["textfield-1013-inputEl"];

        alert( 'User name is ' +userName + ' and password is : '+ password);

    }

});